### ISSUE TITLE
7.4b3 just spins, never displays UI

### ISSUE THREAD

**Issue by JetForMe** [insidegui/WWDC#666] opened 2023-02-09 00:15 UTC
- Version of macOS: 13.1
- Version of the app: 7.4b3
- What were you trying to do when the issue happened: launch app to watch video
- Any particular hardware/software configuration you have that might be affecting the app
- If it is a wrong behavior, list all steps required to reproduce it
    - Launch app
    - Tab bar comes up, spinner shows, nothing more. You can select tabs, nothing else changes.
- Please add screenshots if you think they might help us diagnose the issue

<img width="1906" alt="Screenshot 2023-02-08 at 16 14 21" src="https://user-images.githubusercontent.com/401600/217681199-6f65a50a-c55f-4efe-a383-981a11d24ec7.png">

**Comment by jmsy** [comment] 2023-02-13 08:13
The same issue on my side. 
Mac OS 13.2
WWDC 7.3.3

**Comment by ararezaee** [comment] 2023-02-16 21:01
Same issue

**Comment by insidegui** [comment] 2023-06-06 18:33
Closing this since I believe it's a duplicate of #665, even though that issue was a crash and not an infinite loading spinner, the issues were related and are both fixed in version 7.4 and its patches.

**Closed by insidegui** 2023-06-06 18:33 UTC

**Comment by JetForMe** [comment] 2023-06-06 21:15
Seems to be fixed, thanks!
