### ISSUE TITLE
Titles in share pop-up have wrong colors

### ISSUE THREAD

**Issue by casperriboe** [insidegui/WWDC#692] opened 2023-06-07 09:35 UTC
### Before opening your issue, please make sure you answer YES to all of the questions below.

- Are you running the latest version of the app? **Yes**
- Are you running a release, stable version of macOS? **Yes, Ventura 13.4**
- Have you looked at previous issues to see if you're having an issue that's already being worked on? **Yes**
- If your issue is about compilation or project setup, have you followed the instructions from the readme? **N/A**
- Have you read the Code of Conduct, and will you uphold its values? **Yes**

### If you answered YES to all of the questions, please provide as much information as possible about your issue.

- Version of macOS **14.0 Beta (23A5257q)**
- Version of the app **7.4.2**
- What were you trying to do when the issue happened **Share a video link**
- Any particular hardware/software configuration you have that might be affecting the app **No**
- If it is a crash, please provide the crash log **N/A**
- If it is a hang (beach ball), please provide a process sample **N/A**
- If it is a wrong behavior, list all steps required to reproduce it **See below**
- Please add screenshots if you think they might help us diagnose the issue **See below**

### Description
When running the app using the Light system appearance, the share pop-up has dark titles instead of light titles. However when the system appearance is Dark, the titles are correctly light as they should. It looks like they aren't hardcoded like the background is, and instead follow the system style.

### Steps to reproduce
- Use the macOS light system appearance (either explicitly or through the Auto setting)
- Go to a video in WWDC
- Click the share icon to the right, below the video
- Observe the issue

### Screenshot
<img width="575" alt="image" src="https://github.com/insidegui/WWDC/assets/27224040/999ca4e8-bbac-49f3-aefc-89ad53593feb">

**Comment by allenhumphreys** [comment] 2023-06-07 15:30
This seems to be related to dark/light mode. I did a little looking, we're using the system sharing picker, nothing special. We do override the app's appearance to be dark. It seems the font in the sharing menu is not honoring the appearance while the background is. Whether there is anything we can do about it would require setting up a blank Mac app and minimally reproduce it. If the bug exists in a standard app, I'd say the only option would be to file a feedback. If it doesn't reproduce in a basic app, then more digging would be required.

The relevant code starts at https://github.com/insidegui/WWDC/blob/master/WWDC/AppCoordinator%2BSessionActions.swift#L153-L164 and it invokes the system share sheet which has a delegate

<img width="258" alt="Screenshot 2023-06-07 at 11 02 21 AM" src="https://github.com/insidegui/WWDC/assets/8225090/4bff52b7-b405-480b-872b-d11584ac43ed">

**Comment by allenhumphreys** [comment] 2023-06-07 16:02
Gonna leave this here, not sure if we'll do it, but I was able to hack the pop over window to override it's appearance with reasonable results:

```swift
NotificationCenter.default.publisher(for: NSApplication.willUpdateNotification).sink { note in
    guard let windows = (note.object as? NSApplication)?.windows else { return }
    windows.filter { window in
        guard let popOverClass = NSClassFromString("_NSPopoverWindow") else { return false }
        guard let shareSheetViewControllerClass = NSClassFromString("SHKShareSheetRemoteViewController") else { return false }
        return window.isKind(of: popOverClass) && window.contentViewController?.isKind(of: shareSheetViewControllerClass) == true
    }
    .forEach {
        $0.appearance = NSAppearance(named: .darkAqua)
    }
}.store(in: &self.cancellables)
```

**Comment by insidegui** [comment] 2023-06-07 20:18
Here's another potential solution that covers all popovers in the app (since we definitely want all poppers to inherit the dark appearance):

```swift
@objcMembers final class DarkPopover: NSWindow {
    static var darkAppearance: NSAppearance? { NSAppearance(named: .darkAqua) }

    static func install() {
        guard let target = NSClassFromString("_NSPopoverWindow") else { return }
        guard let original = class_getInstanceMethod(target, #selector(getter: NSWindow.appearance)) else { return }
        guard let replacement = class_getClassMethod(DarkPopover.self, #selector(getter: DarkPopover.darkAppearance)) else { return }

        method_exchangeImplementations(original, replacement)
    }
}
```

**Comment by insidegui** [comment] 2024-05-30 17:09
Closing this as it's been fixed by Apple.

**Closed by insidegui** 2024-05-30 17:09 UTC
