### ISSUE TITLE
The WWDC app is not starting now.

### ISSUE THREAD

**Issue by afixibiranchi** [insidegui/WWDC#247] opened 2017-06-12 12:50 UTC
The app was working fine and i was able to view and download wwdc 2017 session videos.
But its not starting now.
I am running Mac OS Sierra Ver 10.12.5

**Comment by insidegui** [comment] 2017-06-12 12:52
What do you mean by "not starting"?
Does it crash?
If it crashes, does it produce a crash log?
Is there an error message on the screen?
Does it just hang? If it hangs, this is probably a duplicate of #205.

**Comment by insidegui** [comment] 2017-06-14 02:16
I'll close this as invalid. If you have more info please reopen it.

Thanks

**Closed by insidegui** 2017-06-14 02:16 UTC
Labels: invalid
