### ISSUE TITLE
App freezes on launch

### ISSUE THREAD

**Issue by persimmonsoft** [insidegui/WWDC#237] opened 2017-06-09 00:32 UTC
It worked for quite a few launches. I have now downloaded a number of the videos, but now it freezes on launch.
Here is the sample:

[Sample of WWDC.txt](https://github.com/insidegui/WWDC/files/1062753/Sample.of.WWDC.txt)

**Comment by insidegui** [comment] 2017-06-09 03:26
Are you sure this is not a duplicate of #205 ?

**Comment by persimmonsoft** [comment] 2017-06-09 11:25
You are correct, this looks to be a duplicate of #205

**Closed** 2017-06-09 11:25 UTC
