### ISSUE TITLE
UX/UI Tweaks #2

### ISSUE THREAD

**Issue by VicenteBorrell** [insidegui/WWDC#198] opened 2017-05-29 18:11 UTC
- [ ] Replace button with “Play” label with button with Play icon to load video 
- [x] Selecting a bookmark shouldn't start editing, but clicking on the text label
- [x] When selecting multiple options in a filter dropdown, text should be cropped and appended with … (otherwise sidebar keeps getting wider)
- [x] Sidebar can be hidden but can't be shown again (need to restart)
- [ ] Have an <All X> option in dropdowns that resets the dropdown and it's the default (otherwise it's hard to deselect many of the filters)
- [x] Window default size is too tall (conflicts with Dock)

- [x] Can't go fullscreen video from fullscreen app
- [ ] Don't change sessions when closing PiP (clicking X)
- [x] Icons in Top bar: fix size and distance between them and between labels (like in Sketch)

- [x] Change color to white of spinner shown on video load
- [x] Remove thumbnail on Lab Detail view
- [x] Cell separator is missing from the design (I know, it's hard to see :))
- [x] Add tooltip on some video controls (Add Bookmark)
- [x] Use point · (or em dash – ) as separator in Cells (except times like 20:00 - 21:30)
- [ ] Change selected state color in dropdowns to active color

**Comment by VicenteBorrell** [comment] 2017-05-29 18:16
Again, these are less important. They are more or less ordered by priority.
I don't think they'll be hard to fix. I know you have a lot of work to do but if you can fix them it would be great! :)

**Comment by insidegui** [comment] 2017-05-29 18:18
Most of them are simple fixes, I think I can get almost all of them done 😉

**Comment by VicenteBorrell** [comment] 2017-05-29 18:24
Awesome! :)

**Comment by insidegui** [comment] 2017-05-29 22:22
> Can't go fullscreen video from fullscreen app

I was unable to reproduce this

**Comment by insidegui** [comment] 2017-05-29 23:47
> Change selected state color in dropdowns to active color

This is not possible without some serious hacking

**Comment by insidegui** [comment] 2017-05-30 00:49
> Replace “Play” word Play button to load video

Can you elaborate?

**Comment by joshfriend** [comment] 2017-05-30 12:35
Can the "lab" sessions be hidden by default? They have no video and make up the majority of the sessions in the schedule. The majority of people using this app are probably not attending WWDC, so they won't care when the labs are. The official WWDC iOS app already shows lab times for the people who actually do care.

**Comment by insidegui** [comment] 2017-05-30 13:10
I was already thinking about adding a preference to hide labs, sounds like a good idea. What do you think @VicenteBorrell ?

**Comment by VicenteBorrell** [comment] 2017-05-30 15:52
@insidegui 
- When you go fullscreen window, the icon to go fullscreen video disappears 
- I was talking about the background selection color (currently blue). No problem 👍 
- I was referring to the Play button on the video before it starts playing

Yeah, we could hide Labs by default, but that wouldn't be the expected behavior @joshfriend 
I think they can be visually skipped very easily. Maybe after the conference we can filter them by default, and have Sessions selected instead of All Events @insidegui

**Comment by VicenteBorrell** [comment] 2017-06-04 15:15
The sidebar can be hidden with by dragging the separator and the action to show it again is not enabled on the View menu @insidegui

**Comment by insidegui** [comment] 2017-07-06 14:11
@VicenteBorrell I'm going to close this since most of it is outdated. Please open another one if there are any other tweaks we need to make.

**Closed by insidegui** 2017-07-06 14:11 UTC
Labels: ux

**Comment by VicenteBorrell** [comment] 2017-07-07 10:02
OK!
