### ISSUE TITLE
100% CPU usage in some cases after waking computer up? (possibly related to background downloads)

### ISSUE THREAD

**Issue by DimaVartanian** [insidegui/WWDC#147] opened 2016-06-15 15:38 UTC
I left the WWDC app running last night and put my computer to sleep. When I woke it up this morning, everything was halted to a stand still. I was able to open the activity monitor and saw that the WWDC app was using 115% CPU with 21 threads (not sure how relevant that second bit is but it seems to be using about half those threads under normal conditions). All other apps were using their normal amounts of 0-2%. I was able to force quit it and after restarting it, it was back to a reasonable 1%. I can't repro the issue now with putting the computer to sleep so I'm not sure why it happened, but it definitely happened.

**Comment by insidegui** [comment] 2016-06-15 15:40
Who knows, that's a hard one to reproduce, debug and fix, definitely not gonna have time for It now. Thanks for reporting tho.

**Comment by DimaVartanian** [comment] 2016-06-15 15:46
Yeah just wanted to get a record of it in case it comes up again later, no worries :)

**Comment by pahnev** [comment] 2016-07-22 06:29
I had similar experience. I set the app to download a bunch of sessions and then put the computer to sleep. When I woke the computer the downloads were no longer progressing.

I just quit the app and forgot about the whole thing. Next morning after a while, I started getting warning that my disk was almost full. The downloads started again, but for some reason they were filling up the cache folder `~Libary/Caches/com.apple.nsurlsessiond/Downloads/br.com.guilhermerambo.WWDC` had bunch of files and activity monitor showed that it nsurlsessiond was receiving gigabytes of data.

I don't know what would be solution for this, just thought that I let you know :)

**Comment by insidegui** [comment] 2016-07-22 14:02
Looks like an issue with Apple's `NSURLSession` background downloads, I'll search around and see if anyone has had this problem before. Thanks for the information.

**Comment by insidegui** [comment] 2017-05-29 18:25
Because of this (and other related issues), v5 doesn't have batch downloads anymore. Thanks for reporting!

I'm closing this issue since it is not applicable anymore with the release of v5.

Version 5 is available as a pre release download now and users of the previous version will get the automatic update later this week. [wwdc.io](https://wwdc.io)

**Closed by insidegui** 2017-05-29 18:25 UTC
Labels: bug
