### ISSUE TITLE
The app freeze everytime it's launched

### ISSUE THREAD

**Issue by icenel** [insidegui/WWDC#284] opened 2017-08-13 01:26 UTC
For the first time I launched the app, it displayed a spinner, and there was no way to quit unless than using force quit. For the second time and so on, it displays the last displayed video, and just stuck there. The app becomes unresponsive and I can't click anything in the window.

I've tried to clear the data in `~/Library` but it still doesn't work after reinstalling.

Stacks: (this also include app version & system info)
[WWDC_2017-08-12-110902_Edwards-iMac.hang.zip](https://github.com/bustoutsolutions/siesta/files/1219695/WWDC_2017-08-12-110902_Edwards-iMac.hang.zip)

**Comment by donly** [comment] 2017-08-24 03:52
The same issue here

**Comment by insidegui** [comment] 2017-08-24 14:51
We had this issue a couple of versions ago and we managed to fix it for most users. Currently we're waiting for a reproduction so we can see what's going on. Without reproducing it, we can't really do anything.

**Comment by icenel** [comment] 2017-09-01 15:22
@insidegui  I don't know if this would help but I managed to fix it myself by running
`./cleardata.sh`.

**Comment by insidegui** [comment] 2017-09-01 20:22
You probably had a corrupt database. This happened to a few people and got fixed with an update. I didn't suggest you to run it because you mentioned cleaning the data in `~/Library` 😅

**Comment by icenel** [comment] 2017-09-02 16:37
Thank you for your response.
I did clean the `~/Library/Application Support` and also tried reinstalling the app, restarting the mac, but nothing worked. The only thing that worked was `./cleardata.sh`.
This happened after I upgrade from the old version (the one that doesn't have black background theme) to the new version. (Sorry I don't remember the exact version)

**Comment by insidegui** [comment] 2017-09-02 22:06
That's interesting. Did you have any downloaded videos from the previous version?

**Comment by donly** [comment] 2017-09-04 01:27
Thanks, clean using `./cleardata.sh` is works for me too.

**Comment by bcmn** [comment] 2017-09-05 12:39
Had you manually changed your downloads destination directory on the previous version?

Alternatively, it may be beneficial to send us a copy of ~/Library/Preferences/io.wwdc.app.plist from the time at which you encountered this issue -- perhaps through time machine?

**Comment by icenel** [comment] 2017-09-06 12:53
@insidegui Yes, I had like 3 downloaded videos.

**Comment by insidegui** [comment] 2017-09-06 13:06
Thanks for the feedback. We'll do some testing around this, we think the migration is the cause and it could be related to downloads.

**Comment by YangJun16** [comment] 2017-09-14 15:12
I encountered the same issue. It has confused me for several months. I upgraded it from WWDC 2016(old version) to WWDC 2017 5.1.1. Everything is OK. It seems that the downloads destination directory of WWDC 2017 diverges from the downloads destination directory of WWDC 2016. I changed the dir of WWDC 2017 owing to previous videos. The dir is ~/Library/Application Support/WWDC. There was nothing wrong with it until I upgraded it to 5.1.2. It has no response as soon as I launch it. It no longer works since then, although I upgraded it to 5.2.0. I haven't deleted any file or dir about WWDC in ~/Library yet. I searched for WWDC in ~/Library and got three dirs(br.com.guilhermerambo.WWDC, io.wwdc.app.TranscriptIndexingService, WWDC), one package(io.wwdc) and one .plist file(WWDC_9F8EFE1B-D8EC-526F-8F84-D0C6DA94793D). io.wwdc can't be opened when I double-click it. I'm not sure how it should be. I didn't enable time machine. I hope that my description could help you. If you have any other question, let me tell. @

**Comment by YangJun16** [comment] 2017-09-14 15:13
I encountered the same issue. It has confused me for several months. I upgraded it from WWDC 2016(old version) to WWDC 2017 5.1.1. Everything is OK. It seems that the downloads destination directory of WWDC 2017 diverges from the downloads destination directory of WWDC 2016. I changed the dir of WWDC 2017 owing to previous videos. The dir is ~/Library/Application Support/WWDC. There was nothing wrong with it until I upgraded it to 5.1.2. It has no response as soon as I launch it. It no longer works since then, although I upgraded it to 5.2.0. I haven't deleted any file or dir about WWDC in ~/Library yet. I searched for WWDC in ~/Library and got three dirs(br.com.guilhermerambo.WWDC, io.wwdc.app.TranscriptIndexingService, WWDC), one package(io.wwdc) and one .plist file(WWDC_9F8EFE1B-D8EC-526F-8F84-D0C6DA94793D). io.wwdc can't be opened when I double-click it. I'm not sure how it should be. I didn't enable time machine. I hope that my description could help you. If you have any other question, let me tell. @insidegui

**Comment by insidegui** [comment] 2017-09-14 15:53
Thanks for your report @YangJun16 !

Can you zip the folder in `~/Library/Application Support/br.com.guilhermerambo.WWDC` and send it to me?

If you don't want to upload it publicly, you can e-mail it to `eu [at] guilhermerambo.me`

**Comment by YangJun16** [comment] 2017-09-14 17:58
Of course! I sent it to eu@guilhermerambo.me @icenel !

**Comment by insidegui** [comment] 2017-09-24 13:00
TODO: 
- [ ] After the Swift 4 update, test the app with the prefs and database provided by @YangJun16

**Comment by antonselyanin** [comment] 2017-10-22 05:57
I tried to reproduce the issue, but could't make the app freeze on startup

What I did:
- removed existing db and plist files ('io.wwdc.app' folder and 'io.wwdc.app.plist' file)
- copied the provided files
- checked out 5.1.1, compiled and run
- checked out 5.1.2, compiled run
- checked out 5.2.0, compiled run
- checked out master version, compiled and run
the app worked on all stages, I even tried step by step debugging to make sure that the migration was actually being executed

Maybe, it's not just the database

**Comment by insidegui** [comment] 2017-10-22 13:43
@antonselyanin Have you tried having some downloaded sessions during the migration? I believe this issue has something to do with the migration of old downloaded sessions stored outside the default download folder.

**Comment by antonselyanin** [comment] 2017-10-22 13:55
Good point, I'll try it

**Comment by YangJun16** [comment] 2017-10-23 15:18
Have you reproduced the issue with my prefs and db @insidegui ?

**Comment by insidegui** [comment] 2017-10-23 16:35
@YangJun16 Nope

**Comment by insidegui** [comment] 2018-05-26 21:03
I'll close this issue since we haven't been able to reproduce it and there's no new activity. If anyone is still having this issue and can point us towards a path for reproduction, please comment. Thanks!

**Closed by insidegui** 2018-05-26 21:03 UTC
Labels: bug: crash, needs reproduction

**Comment by BubiDevs** [comment] 2018-06-11 07:30
Some here, every time I open the app it freeze.

Can I send to you some useful Information?

**Comment by insidegui** [comment] 2018-06-11 14:44
We have open issues for this, @allenhumphreys is looking into it.

**Comment by insidegui** [comment] 2018-06-13 16:48
Keep an eye on #464 for updates on this.
