### ISSUE TITLE
Fullscreen Video Disappears when Switching Selected Session

### ISSUE THREAD

**Issue by grantjbutler** [insidegui/WWDC#433] opened 2018-06-07 17:14 UTC
- Version of macOS: **macOS High Sierra 10.13.3 (17D47)** 
- Version of the app: **WWDC 6.0.3**

When watching a video in full screen, if I select another session in the app, then switch back to the full screen video, I'm presented with a black screen. However, the video is still playing, as I continue to hear the audio. If I select the session I'm watching, then switch back to the full screen video, then the video appears.

**Comment by allenhumphreys** [comment] 2018-06-07 17:52
Duplicate of #418

**Closed by allenhumphreys** 2018-06-07 17:52 UTC
