### ISSUE TITLE
Sidebar selected item's text unreadable under light mode

### ISSUE THREAD

**Issue by alphachung** [insidegui/WWDC#546] opened 2019-05-29 19:43 UTC
### Before opening your issue, please make sure you answer YES to all of the questions below.

- [x] Are you running the latest version of the app?
- [x] Are you running a release, stable version of macOS?
- [x] Have you looked at previous issues to see if you're having an issue that's already being worked on?
- [x] If your issue is about compilation or project setup, have you followed the instructions from the readme?
- [x] Have you read the Code of Conduct, and will you uphold it's values?

### If you answered YES to all of the questions, please provide as much information as possible about your issue.

- Version of macOS
    - 10.14.5
- Version of the app
    - 6.1.2
- What were you trying to do when the issue happened
    - I opened the app under light mode, and the background colour of the selected item in the sidebar appears too light to read the text. 
- If it is a wrong behavior, list all steps required to reproduce it
    1. Switch to light mode
    2. Open the app
- Please add screenshots if you think they might help us diagnose the issue
<img width="1407" alt="BE6641D8-E349-4DA6-A3F3-42610E35C729" src="https://user-images.githubusercontent.com/5276387/58585869-5be0c400-828c-11e9-91fc-f7b9bf40716c.png">

**Comment by mediter** [comment] 2019-05-30 02:48
Similar to #527

**Comment by insidegui** [comment] 2019-05-31 03:37
Closing this as a duplicate of #527

**Closed by insidegui** 2019-05-31 03:37 UTC
Labels: bug, ux
