### ISSUE TITLE
Sound sometimes cuts out for a couple of seconds when seeking back with the button

### ISSUE THREAD

**Issue by balazsgerlei** [insidegui/WWDC#266] opened 2017-06-27 09:29 UTC
- Version of macOS
10.12.5
- Version of the app
5.1.2
- What were you trying to do when the issue happened
When I am watching a video, sometimes when I seek back with the back button, the sound cuts out for a couple of seconds. I was unable to find out what causes it, but as I remember I always experienced it while watching a video full screen with the speed set to 1.25x.
- If it is a wrong behavior, list all steps required to reproduce it
Sadly I still haven't found a way to deterministically reproduce the issue. It does not happen all the times, and I don't know what steps may cause it to happen.

**Comment by insidegui** [comment] 2017-06-27 12:11
Does this happen with streaming videos, downloaded videos or both? Sounds like a normal thing when seeking streaming videos...

**Comment by balazsgerlei** [comment] 2017-06-27 13:46
It definitely happened with a downloaded video. And I'm not talking about 1-2 seconds, but rather 5-10. It is very rare though, I will try to find out exactly when it happens and report back!

**Comment by insidegui** [comment] 2017-06-27 16:18
We've had a [PR recently](https://github.com/insidegui/WWDC/pull/243) that changed something about how `AVPlayer` handles audio, I wonder if that's the cause. 🤔

**Comment by antonselyanin** [comment] 2017-08-14 17:30
This happens quite often to me and it's very annoying. I tried commenting out changes from #243 PR but the issue persisted.

I managed to reproduce video/audio sync issue (although I'm not sure it's the same issue)

* Install "Network Link Conditioner", create a custom profile with 2200 kbps downlink bandwidth.
* Start playing a video, make sure it's playing on high quality
* Enable 2200 kbps limit, the video quality should downgrade and the syncing issue should appear (no audio for several seconds).

**Comment by insidegui** [comment] 2017-08-15 17:22
If that's the case, it seems to be an issue with `AVFoundation` and/or Apple's streaming. If it turns out to be, all we can do is file radars I guess. 😬

**Comment by allenhumphreys** [comment] 2017-08-15 18:41
I'd be curious if this behaves differently in High Sierra. Assuming the work AVFoundation has received for iOS 11 is also going to be in High Sierra, it seems that HLS got a lot of attention. I'm concerned that @balazsgerlei said that it happened in a downloaded video because during my testing with the change of the audio algorithm, I specifically noticed much worse performance when streaming vs local playback. That is why when you change the playback speed, there is a `seek(to:)` the current time. IIRC that was only needed for the streaming case.

As it stands, I can't seem to reproduce the issue. There is a super slim possibility that it is a hardware specific issue (i.e. different generation Macs have different drivers that might have different bugs in them). 

If there is any chance the issue is related to tapping the skip back button several times in rapid succession, it might make sense to do the following

```
player.currentItem?.cancelPendingSeeks()
player.seek(to: targetTime) 
```

I also see that annotations don't use the time scale of the player when seeking to a time. `let time = CMTimeMakeWithSeconds(Float64(annotation.timestamp), 9000)`. But that shouldn't really be an issue since the player should do the necessary translation for you.

Another thought is to provide some options when loading up the `AVPlayer` like this:

```
let asset = AVURLAsset(url: finalUrl, options: [AVURLAssetPreferPreciseDurationAndTimingKey : true])
let item = AVPlayerItem(asset: asset)
self.player = AVPlayer(playerItem: item)
```

This might improve the behavior while seeking, but _**might**_ also result in seeks and/or the initial load time taking longer.

@antonselyanin or @balazsgerlei could you guys investigate some of these changes for any improvements in your reproduction cases?

**Comment by insidegui** [comment] 2017-08-16 13:41
```
There is a super slim possibility that it is a hardware specific issue (i.e. different generation Macs have different drivers that might have different bugs in them).
```

This sounds plausible. I don't think I've ever experienced this issue on my early 2013 MacBook Pro.

**Comment by bcmn** [comment] 2017-08-17 18:50
> I'd be curious if this behaves differently in High Sierra.

For what it's worth, using Network Link Conditioner as @antonselyanin suggested, I have seen this on High Sierra.

**Comment by insidegui** [comment] 2017-09-24 13:11
Okay, so it sounds like (ha) this is an issue with `AVFoundation`'s handling of >1x playback on slow networks. I think we have two options:
1 - DTS
2 - Someone file a radar and we all dupe it and send to our friends at Apple

As this doesn't seem like an issue in the app itself, I'm going to close this. If anyone happens to find a solution or workaround, please let me know.

**Closed by insidegui** 2017-09-24 13:11 UTC
Labels: bug, player
