### ISSUE TITLE
Can’t cast 2018 videos

### ISSUE THREAD

**Issue by pahnev** [insidegui/WWDC#444] opened 2018-06-08 15:46 UTC
Trying to cast any of the 2018 videos to Chromecast fails with an error `The data couldn’t be read because it isn’t in the correct format.`. 

<img width="532" alt="screen shot 2018-06-08 at 18 41 49" src="https://user-images.githubusercontent.com/2078494/41167621-24f78954-6b4c-11e8-9c2e-08b5a484b6bd.png">

Running macOS 10.13.5. 
Version of the WWDC app: 6.0.3
Chromecast firmware version: 1.29.104827

**Comment by insidegui** [comment] 2018-06-08 15:56
Which ChromeCast device are you using?

**Comment by pahnev** [comment] 2018-06-08 16:22
The 2nd generation one https://store.google.com/product/chromecast_2015

**Comment by fredsco** [comment] 2018-06-10 19:35
I have the same issue. 😢

**Comment by fredsco** [comment] 2018-06-10 20:54
@bcmn yes it happens consistently.

**Comment by pahnev** [comment] 2018-06-11 06:49
Yup consistent here too. Tried multiple videos and same error on all.

Just fyi. Made a quick hack for iOS using Google’s SDK and the 2018 videos work fine. https://github.com/pahnev/WWDC-ios-caster

**Comment by insidegui** [comment] 2018-06-11 14:45
> Just fyi. Made a quick hack for iOS using Google’s SDK and the 2018 videos work fine.

We use a custom ChromeCast integration because the Cast SDK is not available for macOS.

I need someone to capture more detailed information about the error so we can figure it out, since I can't reproduce it here with my ChromeCast setup.

**Comment by fredsco** [comment] 2018-06-11 15:31
I would like to help, what should I do?


On 11 Jun 2018, at 16:46, Guilherme Rambo <notifications@github.com<mailto:notifications@github.com>> wrote:


Just fyi. Made a quick hack for iOS using Google’s SDK and the 2018 videos work fine.

We use a custom ChromeCast integration because the Cast SDK is not available for macOS.

I need someone to capture more detailed information about the error so we can figure it out, since I can't reproduce it here with my ChromeCast setup.

**Comment by insidegui** [comment] 2018-06-11 21:23
Are you able to run the app from Xcode? If you are, do that and filter in the Console app for the subsystem `ChromeCastCore`.
<img width="548" alt="image" src="https://user-images.githubusercontent.com/67184/41257792-86429fb4-6da4-11e8-9b8b-8bb102435f03.png">

**Comment by pahnev** [comment] 2018-06-12 10:05
![screen shot 2018-06-12 at 13 04 50](https://user-images.githubusercontent.com/2078494/41284180-3c74ec0a-6e41-11e8-9ba4-12bbc93eb522.png)

**Comment by insidegui** [comment] 2018-06-12 13:16
@pahnev Thank you! I'm not sure that's the root cause of the issue, but now I can investigate this further.

**Comment by insidegui** [comment] 2018-08-11 16:02
I made a potential fix for this issue in ChromeCastCore 0.3, it should be fixed on the next update.

**Closed** 2019-05-02 17:23 UTC
Labels: bug
