### ISSUE TITLE
The macOS 10.12.6 WWDC5.3 version prompt does not respond. Why does it happen?

### ISSUE THREAD

**Issue by ChinaHackers** [insidegui/WWDC#370] opened 2018-05-01 17:24 UTC
- Version of macOS : 10.12.6
- Version of the app: 5.3

The macOS 10.12.6 WWDC5.3 version prompt does not respond.
Why does it happen?

### Please reply to how to solve this problem.

**Comment by insidegui** [comment] 2018-05-26 21:01
@ChinaHackers Hi! Can you please describe your problem in more detail? Thank you!

**Comment by ChinaHackers** [comment] 2018-05-27 03:12
@insidegui Open the WWDC mouse to be a busy state ----> wind fire wheel.

**Comment by insidegui** [comment] 2018-05-31 14:04
@ChinaHackers Can you try version 6 and see if you still have the same issue? Thanks

**Comment by ChinaHackers** [comment] 2018-05-31 14:39
@insidegui   I tried it a few hours ago. It's the same bug.. Do you want to upgrade High Sierra?

**Comment by insidegui** [comment] 2018-06-13 16:47
I'm closing this as a duplicate of #464, look for updates there.

**Closed by insidegui** 2018-06-13 16:47 UTC
Labels: waiting reply
