### ISSUE TITLE
Unwatched filter not working

### ISSUE THREAD

**Issue by Logistes** [insidegui/WWDC#579] opened 2019-07-22 02:00 UTC
My MBP is running macOS 10.15 Beta (19A512f)
I'm running WWDC Version 6.1.2 

I have been going through the videos I wanted to see, using the filters Downloaded and Unwatched to ensure that I was always getting new one. But for a while the Unwatched filter has not been working. It could be that it stopped when I installed 10.15. Now, after watching a video to the end, it still shows up even when I have Unwatched switched on.

The videos I watched earlier are excluded and if I turn the Unwatched filter off, those ones come back to the list.

**Comment by insidegui** [comment] 2020-07-20 23:08
Closing this since we haven't been able to reproduce it and the version of the app reported is older than the most current version. Please let us know if you can give reproduction steps in the latest version.

**Closed by insidegui** 2020-07-20 23:08 UTC
Labels: needs reproduction
