### ISSUE TITLE
How to download WWDC2017 videos of  the Chinese subtitles?

### ISSUE THREAD

**Issue by iHTCboy** [insidegui/WWDC#297] opened 2017-08-31 00:46 UTC
new download videos default is 'english CC', no download videos online can select Chinese subtitles. I used Version 5.1.3. thank you!

**Comment by iHTCboy** [comment] 2017-08-31 00:47
fix

**Comment by insidegui** [comment] 2017-08-31 02:01
Duplicate of #267

**Closed by insidegui** 2017-08-31 02:01 UTC
