### ISSUE TITLE
Can't see transcripts

### ISSUE THREAD

**Issue by teogeos** [insidegui/WWDC#651] opened 2021-05-01 19:48 UTC
- Version of macOS: 11.2.3
- Version of the app: 7.2

Hello. I can't see Transcripts for any video. I don't know if I'm missing something here, but I can't see any button or anything to see transcripts. Here is a screenshot of the app on my mac:
<img width="1552" alt="Screenshot 2021-05-01 at 21 42 30" src="https://user-images.githubusercontent.com/9444441/116793352-a09fb600-aac6-11eb-8017-3927819e7600.png">

Also, in the preferences window, Transcript Language is constantly spinning:
<img width="762" alt="Screenshot 2021-05-01 at 21 46 22" src="https://user-images.githubusercontent.com/9444441/116793400-db095300-aac6-11eb-9b06-19544499941a.png">

**Comment by insidegui** [comment] 2021-05-28 19:39
The spinner in the preferences window suggests that transcripts haven't been indexed yet. This could be due to a networking problem that's preventing the app from downloading scripts. After scripts are downloaded, you'll see a new "Transcripts" tab under the video player.

I'll close this issue for now since this seems to be due to a temporary networking issue that prevented the transcripts from downloading. If you find reproducible steps, we can reopen it later.

**Closed by insidegui** 2021-05-28 19:39 UTC
