### ISSUE TITLE
Changing Watched / Unwatched session status update filter until relaunch

### ISSUE THREAD

**Issue by chrislconover** [insidegui/WWDC#574] opened 2019-06-14 22:16 UTC
- Version of macOS: 10.15
- Version of the app 6.1.

Context: 

Left index view provides a context menu for setting watched / unwatched status, which gets around known bugs in watched status. Further, there is a watched / unwatched filter category to show and hide these sessions.

What should happen:
 
With "watched" filter selected, using the context menu to mark a session as watched should remove it from the index.

What happens:

The watched status seems to only be detected by the search filter upon relaunch.

How to test:

In the left / index column, select the unwatched filter.  Then the context menu using a two-finger click (note that the standard control-click is broken, per another bug), and select "mark as watched".

Note that even after marking the session as watched, it remains in the list.

**Comment by insidegui** [comment] 2019-06-15 12:20
I couldn't reproduce this building from master. Can you check @allenhumphreys ?

**Comment by allenhumphreys** [comment] 2019-06-15 17:50
It's very possible the user is experiencing the persistence of an item triggered by whether it is in the active player. Additionally, the "watched" status is based solely on the current progress. So if you're watching a video and it is not past the 97% limit we use and you mark it as "watched" the progress will be quickly updated to match the currently playing progress and it will then no longer be considered "watched".

Here's an example of the auto-updating filter working as expected:
![filtering](https://user-images.githubusercontent.com/8225090/59554637-8c527e80-8f6b-11e9-9a27-da7f3e220975.gif)

And here is an example of playback overriding the "watched" status of a particular session:
![playbackinterference](https://user-images.githubusercontent.com/8225090/59554654-e05d6300-8f6b-11e9-8f0d-fdbfc3708dcf.gif)

There's a pretty complicated interplay with the data models, iCould syncing, and the UI on this particular topic and I really think this edge case is ok.

**Comment by insidegui** [comment] 2019-06-15 20:50
I think the case where a video was manually marked as watched could have some special handling so it doesn't get overridden by the player, but that would require decoupling the progress from the watched/unwatched state so I don't think it's worth the hassle.

Assuming the case reported was caused by one of the examples given by @allenhumphreys, I'm going to close this issue.

**Closed by insidegui** 2019-06-15 20:50 UTC

**Comment by allenhumphreys** [comment] 2019-06-15 20:52
> that would require decoupling the progress from the watched/unwatched state so I don't think it's worth the hassle.  

Agreed
